name: Trigger auto deployment for container-app-gjgwjam3vvmdq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-gjgwjam3vvmdq-AutoDeployTrigger-f63b4636-dd83-4361-abfe-05c0f6580a83.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPGJGWJAM3VVMDQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPGJGWJAM3VVMDQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPGJGWJAM3VVMDQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPGJGWJAM3VVMDQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPGJGWJAM3VVMDQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-gjgwjam3vvmdq
          resourceGroup: appspacesragapp9ba8a320
          imageToBuild: default/container-app-gjgwjam3vvmdq:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


